% Copyright (C) <2026> <Louise REGNIER and Bassam HAJJ>

% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.

% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.

% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <https://gnu.org>.
% Use code with caution.
%%-------------------------------------------
%%

clear all
close all

%% Load file 
% Use this code to open a localization file generated by thunderstorm
% (.csv); shift the frame number by a given number of frame and save it
% as .csv or .txt

[file,path] = uigetfile({'*.csv'},'Select the localization file','F:\Louise\DATA\DATA2023');
filename=fullfile(path,file);
T = readtable(filename,'PreserveVariableNames',true);
results_all = table2array(T);
A_titles = T.Properties.VariableNames;
%% Figure: scatter plot 3d
filter_threshold = results_all(:,8)>0 & results_all(:,8)<2000 ...
    & results_all(:,5)<3000 & results_all(:,5)>0 ...
& results_all(:,4)<1000 & results_all(:,4)>-500 ...   
& results_all(:,10)<6000 & results_all(:,10)>0*160 ...
& results_all(:,11)>0 &results_all(:,11)<110 ;%& results_all(:,11)<100;
    rho_dim = 14;

    %% photons
    px_size_x = 120; px_size_z = 374.6; %nm
    preamp = 15.4; 
    EM=150;

N_photons = results_all(:,5).*results_all(:,8).*results_all(:,9).*results_all(:,10)/(px_size_x*px_size_x*px_size_z)*(2*pi)^(3/2)*(preamp/EM);
figure, histogram(N_photons(:),'BinWidth',50), 
title(['<N_p_h>=' num2str(mean(N_photons(:)),4) '; med(N_p_h)=' num2str(median(N_photons(:)),4)])
xlabel('Number of photons'); ylabel('# of molecules')
xlim([0 15000]); ax=gca; ax.FontSize=12;

%% wobbling
figure, histogram(results_all(:,11),'BinWidth',5), 
title(['wobbling'])
xlabel('\delta_2_D [°]'); ylabel('# of molecules')
xlim([0 180]); ax=gca; ax.FontSize=12;

%% orientation 2D
figure, histogram(results_all(:,rho_dim),'BinWidth',2), 
title(['\rho'])
xlabel('\rho [°]'); ylabel('# of molecules')
xlim([0 180]); ax=gca; ax.FontSize=12;

    %%

     figure(40045), 
scatter3(results_all(filter_threshold,2),results_all(filter_threshold,3),results_all(filter_threshold,4),4,(results_all(filter_threshold,rho_dim)),'filled')
axis equal, axis image, 
xlabel('x [nm]'),ylabel('y [nm]'),zlabel('z [nm]'),colormap hsv,%caxis([0 180])
title({['Results 3D - Color = \rho ']})
colorbar

%% Figure: scatter plot + color code for rho orientation


    figure(786453), 
scatter(results_all(filter_threshold,2),results_all(filter_threshold,3),5,(results_all(filter_threshold,rho_dim)),'filled')
axis equal, axis image, 
xlabel('x [nm]'),ylabel('y [nm]'),zlabel('z [nm]'),colormap hsv,%caxis([0 180])
title({['Results 3D - Color = \rho '],'Select the area to analyze'})
colorbar

%%
h=impoly(gca);
position=wait(h);
position=[position; squeeze(position(1,1)), squeeze(position (1,2))];

%%
in=inpolygon(results_all(:,2),results_all(:,3),position(:,1),position(:,2));
in = in & filter_threshold;

% hold on 
% scatter(results_all(in,2),results_all(in,3),15,(results_all(in,rho_dim)))
% plot(position(:,1),position(:,2))
% hold off
% close( figure(786453))
size_bin = 5;
figure(),
subplot(2,2,[1 2])
scatter(results_all(filter_threshold,2),results_all(filter_threshold,3),3,(results_all(filter_threshold,rho_dim)),'filled'),axis equal, axis image, 
colormap hsv, colorbar
hold on,
scatter(results_all(in,2),results_all(in,3),3,'filled','k');hold on
plot(position(:,1),position(:,2),'r')
hold off
subplot(223)
histogram(results_all(in,rho_dim),0:size_bin:180)
xlabel('\rho [°]'),ylabel('# of occurences'), grid on, grid minor
title({['ROI: Histogram of in plane angles \rho ']})

[M S]= mean_std_angle_0to180(results_all(in,rho_dim))  
subplot(224)
polarhistogram(deg2rad([results_all(in,rho_dim); results_all(in,rho_dim)+180]),360/size_bin)
title({['<\rho> = ' num2str(M) '° \pm ' num2str(S) '°']})
