%%
% Use this code to open a localization file generated by thunderstorm
% (.csv); shift the frame number by a given number of frame and save it
% as .csv or .txt

clear all
close all

% Load file 
[file,path] = uigetfile({'*.csv'},'Select the localization file','F:\Louise\DATA\DATA2023');
filename=fullfile(path,file);
T = readtable(filename,'PreserveVariableNames',true);
A = table2array(T);
A_titles = T.Properties.VariableNames;
%% Define shift (number of frames)
prompt = {'columns (you can specify several columns with same offset)','offset', 'Unit (deg, nm, ...)'};
dlg_title = 'Input';
num_lines = 1;
def = {'14 15 16','60','deg'};
width = inputdlg(prompt,dlg_title,num_lines,def);
columns = str2num(char(width{1}));
offset = str2double(char(width{2}));
% angle = str2double(char(width{3})); 
unit = char(width{3}); 
str_col = num2str(columns(1,1));
for cc = 2:size(columns,2)
    str_col = [str_col '-' num2str(columns(1,cc))];
end
%% Create new table
A_new= A; 
if mean(unit == 'deg')==1
    A_new(:,columns) = 0.5*wrapTo360((A(:,columns)+offset)*2); 
else
    A_new(:,columns) = A(:,columns)+offset;
end

%% Save 
[filename, pathname]=uiputfile({'*.txt' },'Save data with frame shift',[path file(1:end-4) '_Offset' num2str(offset) unit '-col-' str_col]);
file_name_full=fullfile(pathname,[filename(1:end-4),'.txt']);
fid=fopen(file_name_full,'w');
display('Saving data .txt')
[r,s]=size(A_new);
fprintf(fid,['%g' repmat(['\t %g'],1,s-1) '\n'],A_new');
fclose(fid)
display('done')
file_name_full=fullfile(pathname,[filename(1:end-4),'.csv']);
display('Saving data .csv')
A_table = array2table(A_new,'VariableNames',A_titles);
writetable(A_table,file_name_full);
display('done')