%%
% Use this code to open a localization file generated by thunderstorm
% (.csv); shift the frame number by a given number of frame and save it
% as .csv or .txt

clear all
close all

% Load file 
[file,path] = uigetfile({'*.csv'},'Select the localization file','F:\Louise\DATA\DATA2023');
filename=fullfile(path,file);
T = readtable(filename,'PreserveVariableNames',true);
A = table2array(T);

%% Define shift (number of frames)
prompt = {'# of frames to shift'};
dlg_title = 'Input';
num_lines = 1;
def = {'0'};
width = inputdlg(prompt,dlg_title,num_lines,def);
frame_shift=str2double(char(width));

%% Create new table
A_fr = A; 
A_fr(:,1) = A(:,1)+frame_shift; 
A_fr(:,2:4) = A(:,2:4)*120/162.5;


%% Save 
[filename, pathname]=uiputfile({'*.txt' },'Save data with frame shift',path);
file_name_full=fullfile(pathname,[filename(1:end-4),'.txt']);
fid=fopen(file_name_full,'w');
display('Saving data .txt')
[r,s]=size(A_fr);
fprintf(fid,['%g' repmat(['\t %g'],1,s-1) '\n'],A_fr');
fclose(fid)
display('done')
file_name_full=fullfile(pathname,[filename(1:end-4),'.csv']);
A_titles = {'frame' 'x [nm]' 'y [nm]' 'sigma [nm]' 'intensity [photons]' 'offset [photons]' 'bkgstd[photons]' 'chi2' 'uncertainty [nm]'};
display('Saving data .csv')
A_table = array2table(A_fr,'VariableNames',A_titles);
writetable(A_table,file_name_full);
display('done')