%%

clear all
% close all

%% Load file 
% Use this code to open a localization file generated by thunderstorm
% (.csv); shift the frame number by a given number of frame and save it
% as .csv or .txt

% [file,path] = uigetfile({'*.csv'},'Select the localization file','F:\Louise\DATA\DATA2023');
[file,path] = uigetfile({'*.csv'},'Select the localization file','/Volumes/T7 Touch/Louise/DATA/DATA2024');
filename=fullfile(path,file);
T = readtable(filename,'PreserveVariableNames',true);
results_all = table2array(T);
A_titles = T.Properties.VariableNames;
%% Figure: scatter plot 3d
filter_threshold = results_all(:,8)>80 & results_all(:,8)<200 ...
    & results_all(:,5)<3000 & results_all(:,5)>0 ...
& results_all(:,4)<1000 & results_all(:,4)>-500 ...   
& results_all(:,10)<600 & results_all(:,10)>160 ...
& results_all(:,11)>0 &results_all(:,11)<180 ;%& results_all(:,11)<100;
    rho_dim = 14;

     figure(40045), 
scatter3(results_all(filter_threshold,2),results_all(filter_threshold,3),results_all(filter_threshold,4),4,(results_all(filter_threshold,rho_dim)),'filled')
axis equal, axis image, 
xlabel('x [nm]'),ylabel('y [nm]'),zlabel('z [nm]'),colormap hsv,%caxis([0 180])
title({['Results 3D - Color = \rho ']})
colorbar

%% Figure: scatter plot + color code for rho orientation


    figure(786453), 
scatter(results_all(filter_threshold,2),results_all(filter_threshold,3),5,(results_all(filter_threshold,rho_dim)),'filled')
axis equal, axis image, 
xlabel('x [nm]'),ylabel('y [nm]'),zlabel('z [nm]'),colormap hsv,%caxis([0 180])
title({['Results 3D - Color = \rho '],'Select the area to analyze'})
colorbar


h=impoly(gca);
position=wait(h);
position=[position; squeeze(position(1,1)), squeeze(position (1,2))];

%%
in=inpolygon(results_all(:,2),results_all(:,3),position(:,1),position(:,2));
in = in & filter_threshold;

% hold on 
% scatter(results_all(in,2),results_all(in,3),15,(results_all(in,rho_dim)))
% plot(position(:,1),position(:,2))
% hold off
% close( figure(786453))
size_bin = 5;
figure(),
subplot(2,2,[1 2])
scatter(results_all(filter_threshold,2),results_all(filter_threshold,3),3,(results_all(filter_threshold,rho_dim)),'filled'),axis equal, axis image, 
colormap hsv, colorbar
hold on,
scatter(results_all(in,2),results_all(in,3),3,'filled','k');hold on
plot(position(:,1),position(:,2),'r')
hold off
subplot(223)
histogram(results_all(in,rho_dim),0:size_bin:180)
xlabel('\rho [°]'),ylabel('# of occurences'), grid on, grid minor
title({['ROI: Histogram of in plane angles \rho ']})

[M S]= mean_std_angle_0to180(results_all(in,rho_dim))  
subplot(224)
polarhistogram(deg2rad([results_all(in,rho_dim); results_all(in,rho_dim)+180]),360/size_bin)
title({['<\rho> = ' num2str(M) '° \pm ' num2str(S) '°']})
